sonar.projectKey=contractoriq
sonar.projectName=ContractorIQ
sonar.sources=contractoriq-api/src/main
sonar.tests=contractoriq-api/src/test
sonar.java.binaries=contractoriq-api/target/classes
sonar.java.source=17
sonar.sourceEncoding=UTF-8
